name: Android CI

on:
  pull_request:
    branches: 
      - main
      - dev
    types: [opened, reopened]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Garantir permissões ao gradlew
      run: chmod +x gradlew
    - name: Build
      run: ./gradlew build
  tests:
    runs-on: ubuntu-latest
    needs: build
    steps:
     - uses: actions/checkout@v4
     - name: set up JDK 11
       uses: actions/setup-java@v4
       with:
         java-version: '11'
         distribution: 'temurin'
         cache: gradle

     - name: Garantir permissões ao gradlew
       run: chmod +x gradlew
     - name: Execução dos Testes
       run: ./gradlew clean test --info

         
      
